name: "Update work item state when PR is merged"
description: "This action will update work item satte in Azure DevOps when the PR is merged"
author: "Canarys Automations"
branding:
  icon: "activity"
  color: "black"
outputs:
  id:
    description: "Work item state updated"
runs:
  using: "node12"
  main: "index.js"
