name: "GitHub Issues to Azure DevOps"
description: "This action will Sync your GitHub Issue to Azure Boards when an Issue is created or updated"
author: "danhellem"
branding:
  icon: "book-open"
  color: "green"
outputs:
  id:
    description: "id of work item created"
runs:
  using: "node12"
  main: "index.js"
